source 'https://github.com/CocoaPods/Specs.git'

def import_pods
	pod 'GRKAnalytics', :path => '..', :subspecs => ['Fabric']
end

target :ios do
    platform :ios, '7.0'
    import_pods
end

target :osx do
    platform :osx, '10.9'
    import_pods
end

